import { Student, Teacher, AttendanceRecord, ExamGradeRecord, TeacherPayroll, SMSNotification, SchoolNotice, FeePayment, GuardianInquiry, AuditLog } from './types';

export const initialStudents: Student[] = [
  {
    id: "std-001",
    studentCode: "DIMS-2026-0601",
    roll: 1,
    nameEnglish: "Sadia Sultana",
    nameBangla: "সাদিয়া সুলতানা",
    className: "Class 9",
    section: "Padma",
    gender: "female",
    dob: "2010-04-15",
    bloodGroup: "B+",
    birthRegNumber: "20102692015034821",
    religion: "Islam",
    fatherName: "Rafiqul Islam",
    fatherNameBangla: "রফিকুল ইসলাম",
    motherName: "Shamsun Nahar",
    motherNameBangla: "শামসুন নাহার",
    guardianName: "Rafiqul Islam",
    guardianRelation: "Father",
    guardianPhone: "+8801712345678",
    guardianEmail: "rafiq.islam@gmail.com",
    emergencyContact: "+8801819234567",
    presentAddress: "House 14, Road 5, Block B, Dhanmondi, Dhaka",
    permanentAddress: "Vill: Alampur, Post: Sonargaon, Dist: Narayanganj",
    upazila: "Dhanmondi",
    district: "Dhaka",
    admissionDate: "2022-01-10",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80",
    totalFeesDue: 0,
    totalFeesPaid: 18500,
    attendanceRate: 96.8,
    lastExamGPA: 5.00,
    gpa: 5.00,
    extracurricular: {
      clubs: ["Science Club", "English Debating Society", "Red Crescent Youth", "ICT & Robotics Guild"],
      sports: ["Badminton (Singles)", "Chess", "Table Tennis"],
      leadershipRoles: ["Class Prefect (Session 2026)", "Science Club Vice-President"],
      hobbies: ["Robotics Programming", "Calligraphy", "Astronomy & Stargazing", "Creative Writing"],
      achievements: [
        {
          id: "ach-001",
          title: "National Math Olympiad Regional Champion",
          year: 2025,
          category: "olympiad",
          level: "District",
          position: "1st Place (Gold)",
          description: "Ranked 1st in Dhaka South Regional Math Olympiad (Junior Category)."
        },
        {
          id: "ach-002",
          title: "Inter-School Science Fair Best Innovation Award",
          year: 2025,
          category: "science",
          level: "School",
          position: "Champion",
          description: "Project: Smart IoT Flood Alert System for Low-lying Coastal Areas."
        }
      ]
    },
    medicalHistory: {
      bloodGroup: "B+",
      knownAllergies: ["Dust & Pollen", "Cold Agglutinins"],
      chronicConditions: ["Mild Exercise-Induced Asthma"],
      regularMedications: ["Salbutamol Inhaler (100mcg, PRN as needed)"],
      specialNeeds: "Prefers well-ventilated seating near windows during seasonal shifts.",
      primaryPhysicianName: "Dr. M. A. Karim, MBBS, FCPS (Pediatrics)",
      primaryPhysicianPhone: "+8801711223344",
      emergencyMedicalInstructions: "If acute shortness of breath occurs, assist with student's emergency inhaler stored in the school sickbay and immediately notify guardian and Dr. Karim.",
      lastHealthCheckupDate: "2026-02-10",
      vaccinationStatus: "Complete"
    },
    emergencyContactInfo: {
      primaryContact: {
        name: "Rafiqul Islam",
        relation: "Father",
        phonePrimary: "+8801712345678",
        phoneSecondary: "+8801711002288",
        email: "rafiq.islam@gmail.com",
        addressOrWorkplace: "BEXIMCO Corporate HQ, 17 Dhanmondi, Dhaka",
        isAuthorizedForPickup: true
      },
      secondaryContact: {
        name: "Shamsun Nahar",
        relation: "Mother",
        phonePrimary: "+8801819234567",
        phoneSecondary: "+8801912334455",
        email: "shamsun.nahar@yahoo.com",
        addressOrWorkplace: "House 14, Road 5, Block B, Dhanmondi, Dhaka",
        isAuthorizedForPickup: true
      },
      preferredHospital: "Square Hospital / Dhaka Medical College Hospital",
      ambulanceContact: "999 / +8801713377775",
      specialPickupInstructions: "Valid Guardian ID card or prior telephonic SMS authorization required for release."
    },
    previousAcademicRecords: [
      {
        id: "prev-001",
        previousSchoolName: "Dhanmondi Govt. Boys' High School (Junior Wing)",
        schoolAddress: "Road 2, Dhanmondi, Dhaka-1205",
        educationBoard: "Dhaka Board",
        examPassedOrClass: "Class 8 Annual Examination",
        passingYear: 2025,
        rollNumber: "101",
        registrationNumber: "2110294820",
        gpaObtained: 5.00,
        percentageOrMarks: 94.5,
        transferCertificateNo: "TC-DGBHS-2025-084",
        tcDate: "2025-12-28",
        conductRating: "Excellent",
        remarks: "Exemplary academic dedication, outstanding analytical skills and exemplary moral conduct."
      },
      {
        id: "prev-002",
        previousSchoolName: "Ideal School & College (Primary Section)",
        schoolAddress: "Motijheel, Dhaka",
        educationBoard: "Dhaka Board",
        examPassedOrClass: "Primary School Certificate (PSC)",
        passingYear: 2022,
        rollNumber: "2044",
        registrationNumber: "1910248291",
        gpaObtained: 5.00,
        percentageOrMarks: 96.0,
        conductRating: "Excellent",
        remarks: "Board Talentpool Scholarship recipient in Primary Education."
      }
    ]
  },
  {
    id: "std-002",
    studentCode: "DIMS-2026-0602",
    roll: 2,
    nameEnglish: "Tanvir Hasan",
    nameBangla: "তানভীর হাসান",
    className: "Class 9",
    section: "Padma",
    gender: "male",
    dob: "2010-08-22",
    bloodGroup: "O+",
    birthRegNumber: "20102692015098712",
    religion: "Islam",
    fatherName: "Kamrul Hasan",
    fatherNameBangla: "কামরুল হাসান",
    motherName: "Taslima Begum",
    motherNameBangla: "তাসলিমা বেগম",
    guardianName: "Kamrul Hasan",
    guardianRelation: "Father",
    guardianPhone: "+8801819876543",
    guardianEmail: "k.hasan.bd@yahoo.com",
    emergencyContact: "+8801912987654",
    presentAddress: "Flat 4A, Green Garden Tower, Mirpur-10, Dhaka",
    permanentAddress: "Vill: Joydebpur, Dist: Gazipur",
    upazila: "Mirpur",
    district: "Dhaka",
    admissionDate: "2022-01-10",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    totalFeesDue: 1500,
    totalFeesPaid: 17000,
    attendanceRate: 92.4,
    lastExamGPA: 4.88,
    gpa: 4.88,
    extracurricular: {
      clubs: ["English Debate Club", "Bangladesh Scout Troupe", "Sports & Athletics Council"],
      sports: ["Cricket (Right-hand Batsman & Vice-Captain)", "Football (Midfielder)", "Table Tennis"],
      leadershipRoles: ["School Cricket Team Vice-Captain", "Scout Patrol Leader (Tiger Patrol)"],
      hobbies: ["Photography", "Public Speaking", "Guitar & Musical Arts"],
      achievements: [
        {
          id: "ach-003",
          title: "Inter-School Bangla Debate Championship Best Speaker",
          year: 2025,
          category: "debate",
          level: "District",
          position: "Best Speaker (Gold)",
          description: "Awarded Best Debater in the Dhaka Metropolitan Inter-School Debate Gala."
        },
        {
          id: "ach-004",
          title: "Dhaka Division Junior Cricket Trophy",
          year: 2024,
          category: "sports",
          level: "Division",
          position: "Runners Up",
          description: "Scored 64 runs in the divisional championship finals."
        }
      ]
    },
    medicalHistory: {
      bloodGroup: "O+",
      knownAllergies: ["None reported"],
      chronicConditions: ["None"],
      regularMedications: ["None"],
      specialNeeds: "None. Physically fit for high-intensity competitive sports.",
      primaryPhysicianName: "Dr. Shahed Ahmed, MBBS, D-Ortho",
      primaryPhysicianPhone: "+8801817766554",
      emergencyMedicalInstructions: "Standard school emergency first aid protocol. Provide ice pack / compression for athletic sports sprains if needed.",
      lastHealthCheckupDate: "2026-01-20",
      vaccinationStatus: "Complete"
    },
    emergencyContactInfo: {
      primaryContact: {
        name: "Kamrul Hasan",
        relation: "Father",
        phonePrimary: "+8801819876543",
        phoneSecondary: "+8801711998877",
        email: "k.hasan.bd@yahoo.com",
        addressOrWorkplace: "Agrani Bank Mirpur Branch, Dhaka",
        isAuthorizedForPickup: true
      },
      secondaryContact: {
        name: "Zahid Hasan",
        relation: "Paternal Uncle",
        phonePrimary: "+8801912987654",
        addressOrWorkplace: "Mirpur DOHS, Dhaka",
        isAuthorizedForPickup: true
      },
      preferredHospital: "National Institute of Traumatology & Orthopaedics (NITOR) / Mirpur General Hospital",
      ambulanceContact: "999 / +8801711225588",
      specialPickupInstructions: "Father or Uncle authorized for school pickup."
    },
    previousAcademicRecords: [
      {
        id: "prev-003",
        previousSchoolName: "Mirpur Cantonment Public School & College",
        schoolAddress: "Mirpur Cantonment, Dhaka-1216",
        educationBoard: "Dhaka Board",
        examPassedOrClass: "Class 8 Annual Examination",
        passingYear: 2025,
        rollNumber: "08",
        registrationNumber: "2110482910",
        gpaObtained: 4.88,
        percentageOrMarks: 89.2,
        transferCertificateNo: "TC-MCPSC-2025-112",
        tcDate: "2025-12-30",
        conductRating: "Excellent",
        remarks: "Active participant in school sports, articulate speaker, and highly disciplined student."
      }
    ]
  },
  {
    id: "std-003",
    studentCode: "DIMS-2026-0603",
    roll: 3,
    nameEnglish: "Anika Tabassum",
    nameBangla: "আনিকা তাবাসসুম",
    className: "Class 9",
    section: "Padma",
    gender: "female",
    dob: "2011-01-05",
    bloodGroup: "A+",
    birthRegNumber: "20112692015044190",
    religion: "Islam",
    fatherName: "Golam Mostafa",
    fatherNameBangla: "গোলাম মোস্তফা",
    motherName: "Nasrin Akhter",
    motherNameBangla: "নাসরিন আক্তার",
    guardianName: "Nasrin Akhter",
    guardianRelation: "Mother",
    guardianPhone: "+8801911445566",
    guardianEmail: "nasrin.akhter77@gmail.com",
    emergencyContact: "+8801711223344",
    presentAddress: "32/A Kazi Nazrul Islam Avenue, Farmgate, Dhaka",
    permanentAddress: "Vill: Shibpur, Dist: Narsingdi",
    upazila: "Tejgaon",
    district: "Dhaka",
    admissionDate: "2022-01-12",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    totalFeesDue: 0,
    totalFeesPaid: 18500,
    attendanceRate: 98.2,
    lastExamGPA: 5.00,
    gpa: 5.00,
    extracurricular: {
      clubs: ["Bangladesh Girl Guides Association", "Cultural & Recitation Society", "Language & Literature Guild"],
      sports: ["Badminton", "Carrom"],
      leadershipRoles: ["Girl Guide Troop Leader", "Cultural Secretary"],
      hobbies: ["Bangla Poem Recitation", "Classical Vocal Music", "Botanical Gardening"],
      achievements: [
        {
          id: "ach-005",
          title: "National Children's Cultural Award - Poetry Recitation",
          year: 2025,
          category: "cultural",
          level: "National",
          position: "2nd Runner Up (Bronze)",
          description: "Awarded by Bangladesh Shishu Academy in Nazrul Geeti Recitation Category."
        }
      ]
    },
    medicalHistory: {
      bloodGroup: "A+",
      knownAllergies: ["Penicillin Antibiotics", "Sea Shellfish"],
      chronicConditions: ["None"],
      regularMedications: ["None"],
      specialNeeds: "Wears corrective eyeglasses (-1.50 Diopter). Recommend front-row board visibility.",
      primaryPhysicianName: "Dr. Farhana Chowdhury, MBBS, FCPS",
      primaryPhysicianPhone: "+8801719887766",
      emergencyMedicalInstructions: "DO NOT administer Penicillin or Amoxicillin class medications under any medical circumstance due to severe hypersensitivity.",
      lastHealthCheckupDate: "2026-02-01",
      vaccinationStatus: "Complete"
    },
    emergencyContactInfo: {
      primaryContact: {
        name: "Nasrin Akhter",
        relation: "Mother",
        phonePrimary: "+8801911445566",
        phoneSecondary: "+8801711223344",
        email: "nasrin.akhter77@gmail.com",
        addressOrWorkplace: "Senior Teacher, Tejgaon Govt. Girls High School",
        isAuthorizedForPickup: true
      },
      secondaryContact: {
        name: "Golam Mostafa",
        relation: "Father",
        phonePrimary: "+8801711223344",
        addressOrWorkplace: "Farmgate, Dhaka",
        isAuthorizedForPickup: true
      },
      preferredHospital: "Popular Diagnostic & Hospital (Farmgate Branch) / Holy Family Red Crescent Hospital",
      ambulanceContact: "999 / +8801713000000",
      specialPickupInstructions: "Mother or Father must present school ID token."
    },
    previousAcademicRecords: [
      {
        id: "prev-004",
        previousSchoolName: "Viqarunnisa Noon School & College (Farmgate Branch)",
        schoolAddress: "Green Road, Farmgate, Dhaka",
        educationBoard: "Dhaka Board",
        examPassedOrClass: "Class 8 Annual Examination",
        passingYear: 2025,
        rollNumber: "02",
        registrationNumber: "2110849201",
        gpaObtained: 5.00,
        percentageOrMarks: 95.0,
        transferCertificateNo: "TC-VNSC-2025-341",
        tcDate: "2025-12-29",
        conductRating: "Excellent",
        remarks: "Consistently topped academic assessments with flawless 98% attendance record."
      }
    ]
  },
  {
    id: "std-004",
    studentCode: "DIMS-2026-0604",
    roll: 4,
    nameEnglish: "Mahmudur Rahman",
    nameBangla: "মাহমুদুর রহমান",
    className: "Class 9",
    section: "Padma",
    gender: "male",
    dob: "2010-11-19",
    bloodGroup: "AB+",
    birthRegNumber: "20102692015011984",
    religion: "Islam",
    fatherName: "Abdur Rahman",
    fatherNameBangla: "আব্দুর রহমান",
    motherName: "Rabeya Khatun",
    motherNameBangla: "রাবেয়া খাতুন",
    guardianName: "Abdur Rahman",
    guardianRelation: "Father",
    guardianPhone: "+8801715667788",
    guardianEmail: "m.rahman.eng@gmail.com",
    emergencyContact: "+8801678123456",
    presentAddress: "Sector 4, Road 11, Uttara, Dhaka",
    permanentAddress: "Vill: Singair, Dist: Manikganj",
    upazila: "Uttara",
    district: "Dhaka",
    admissionDate: "2022-01-15",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    totalFeesDue: 3000,
    totalFeesPaid: 15500,
    attendanceRate: 88.5,
    lastExamGPA: 4.45,
    gpa: 4.45,
    extracurricular: {
      clubs: ["ICT & Coding Club", "Rover Scout Unit", "Environmental Action Club"],
      sports: ["Football", "Volleyball", "Cycling"],
      leadershipRoles: ["Assistant Scout Patrol Leader"],
      hobbies: ["Web Design", "Tree Plantation & Eco Gardening", "Chess"],
      achievements: [
        {
          id: "ach-006",
          title: "Dhaka Division Tree Plantation Eco-Pledge Award",
          year: 2024,
          category: "other",
          level: "Division",
          position: "Special Recognition",
          description: "Planted 50 native trees around school campus grounds."
        }
      ]
    },
    medicalHistory: {
      bloodGroup: "AB+",
      knownAllergies: ["None"],
      chronicConditions: ["None"],
      regularMedications: ["None"],
      specialNeeds: "None",
      primaryPhysicianName: "Dr. K. M. Moniruzzaman, MBBS",
      primaryPhysicianPhone: "+8801715009988",
      emergencyMedicalInstructions: "Standard protocol. Notify parents immediately in case of illness.",
      lastHealthCheckupDate: "2026-01-15",
      vaccinationStatus: "Complete"
    },
    emergencyContactInfo: {
      primaryContact: {
        name: "Abdur Rahman",
        relation: "Father",
        phonePrimary: "+8801715667788",
        email: "m.rahman.eng@gmail.com",
        addressOrWorkplace: "Sector 4, Uttara, Dhaka",
        isAuthorizedForPickup: true
      },
      secondaryContact: {
        name: "Rabeya Khatun",
        relation: "Mother",
        phonePrimary: "+8801678123456",
        addressOrWorkplace: "Sector 4, Road 11, Uttara, Dhaka",
        isAuthorizedForPickup: true
      },
      preferredHospital: "Kuwait Bangladesh Friendship Government Hospital, Uttara",
      ambulanceContact: "999 / +8801711448899",
      specialPickupInstructions: "Valid school guardian token required."
    },
    previousAcademicRecords: [
      {
        id: "prev-005",
        previousSchoolName: "Uttara High School and College",
        schoolAddress: "Sector 7, Uttara, Dhaka",
        educationBoard: "Dhaka Board",
        examPassedOrClass: "Class 8 Annual",
        passingYear: 2025,
        rollNumber: "15",
        gpaObtained: 4.45,
        conductRating: "Good"
      }
    ]
  },
  {
    id: "std-005",
    studentCode: "DIMS-2026-0605",
    roll: 5,
    nameEnglish: "Nusrat Jahan",
    nameBangla: "নুসরাত জাহান",
    className: "Class 9",
    section: "Padma",
    gender: "female",
    dob: "2010-09-30",
    bloodGroup: "O-",
    birthRegNumber: "20102692015065432",
    religion: "Islam",
    fatherName: "Shahidul Alam",
    fatherNameBangla: "শহিদুল আলম",
    motherName: "Farhana Parveen",
    motherNameBangla: "ফারহানা পারভীন",
    guardianName: "Shahidul Alam",
    guardianRelation: "Father",
    guardianPhone: "+8801301223344",
    emergencyContact: "+8801711889900",
    presentAddress: "House 28, Road 2, Banasree, Rampura, Dhaka",
    permanentAddress: "Vill: Chhagalnaiya, Dist: Feni",
    upazila: "Rampura",
    district: "Dhaka",
    admissionDate: "2022-01-10",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    totalFeesDue: 0,
    totalFeesPaid: 18500,
    attendanceRate: 94.0,
    lastExamGPA: 4.75,
    gpa: 4.75,
    extracurricular: {
      clubs: ["Red Crescent Youth Unit", "Math & Logic Club", "Art & Craft Society"],
      sports: ["Badminton", "Handball"],
      leadershipRoles: ["Red Crescent First Aid Volunteer"],
      hobbies: ["Oil Painting", "Origami", "Reading Historical Novels"],
      achievements: [
        {
          id: "ach-007",
          title: "District Art Competition on National Independence Day",
          year: 2025,
          category: "cultural",
          level: "District",
          position: "1st Place",
          description: "Won gold medal for canvas artwork celebrating Bangladesh Liberation War history."
        }
      ]
    },
    medicalHistory: {
      bloodGroup: "O-",
      knownAllergies: ["Sulfa Drugs"],
      chronicConditions: ["None"],
      regularMedications: ["None"],
      specialNeeds: "Rare O-negative blood donor match registered with Red Crescent.",
      primaryPhysicianName: "Dr. S. M. Rezaul Karim, MBBS",
      primaryPhysicianPhone: "+8801712884433",
      emergencyMedicalInstructions: "Rare Blood Group (O-). In case of severe trauma, immediately alert emergency blood bank.",
      lastHealthCheckupDate: "2026-02-15",
      vaccinationStatus: "Complete"
    },
    emergencyContactInfo: {
      primaryContact: {
        name: "Shahidul Alam",
        relation: "Father",
        phonePrimary: "+8801301223344",
        addressOrWorkplace: "Banasree, Rampura, Dhaka",
        isAuthorizedForPickup: true
      },
      secondaryContact: {
        name: "Farhana Parveen",
        relation: "Mother",
        phonePrimary: "+8801711889900",
        addressOrWorkplace: "Banasree, Dhaka",
        isAuthorizedForPickup: true
      },
      preferredHospital: "Farazy Hospital, Banasree / Dhaka Medical College Hospital",
      ambulanceContact: "999 / +8801713334455"
    },
    previousAcademicRecords: [
      {
        id: "prev-006",
        previousSchoolName: "National Ideal School, Khilgaon",
        educationBoard: "Dhaka Board",
        examPassedOrClass: "Class 8 Annual",
        passingYear: 2025,
        gpaObtained: 4.75,
        conductRating: "Excellent"
      }
    ]
  },
  {
    id: "std-006",
    studentCode: "DIMS-2026-0606",
    roll: 6,
    nameEnglish: "Pritom Roy",
    nameBangla: "প্রীতম রায়",
    className: "Class 9",
    section: "Padma",
    gender: "male",
    dob: "2010-06-14",
    bloodGroup: "B+",
    birthRegNumber: "20102692015077651",
    religion: "Hinduism",
    fatherName: "Subhash Roy",
    fatherNameBangla: "সুভাষ রায়",
    motherName: "Kalyani Roy",
    motherNameBangla: "কল্যাণী রায়",
    guardianName: "Subhash Roy",
    guardianRelation: "Father",
    guardianPhone: "+8801718990011",
    emergencyContact: "+8801817654321",
    presentAddress: "Shankhari Bazar, Kotwali, Old Dhaka",
    permanentAddress: "Vill: Muktagacha, Dist: Mymensingh",
    upazila: "Kotwali",
    district: "Dhaka",
    admissionDate: "2022-01-11",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    totalFeesDue: 0,
    totalFeesPaid: 18500,
    attendanceRate: 91.0,
    lastExamGPA: 4.55,
    gpa: 4.55,
    extracurricular: {
      clubs: ["Music & Classical Arts Society", "Chess Club"],
      sports: ["Cricket", "Chess"],
      leadershipRoles: ["Chess Club Captain"],
      hobbies: ["Playing Tabla & Sitar", "Vedic Mathematics"],
      achievements: [
        {
          id: "ach-008",
          title: "Dhaka South Rapid Chess Tournament",
          year: 2025,
          category: "sports",
          level: "District",
          position: "3rd Place",
          description: "Ranked 3rd in under-16 category rapid chess circuit."
        }
      ]
    },
    medicalHistory: {
      bloodGroup: "B+",
      knownAllergies: ["None"],
      chronicConditions: ["None"],
      regularMedications: ["None"],
      primaryPhysicianName: "Dr. B. K. Sarkar, MBBS",
      primaryPhysicianPhone: "+8801711665544",
      lastHealthCheckupDate: "2026-01-10",
      vaccinationStatus: "Complete"
    },
    emergencyContactInfo: {
      primaryContact: {
        name: "Subhash Roy",
        relation: "Father",
        phonePrimary: "+8801718990011",
        addressOrWorkplace: "Shankhari Bazar, Old Dhaka",
        isAuthorizedForPickup: true
      },
      secondaryContact: {
        name: "Kalyani Roy",
        relation: "Mother",
        phonePrimary: "+8801817654321",
        addressOrWorkplace: "Old Dhaka",
        isAuthorizedForPickup: true
      },
      preferredHospital: "Mitford Hospital (Sir Salimullah Medical College), Old Dhaka",
      ambulanceContact: "999"
    },
    previousAcademicRecords: [
      {
        id: "prev-007",
        previousSchoolName: "Pogose Laboratory School and College",
        educationBoard: "Dhaka Board",
        examPassedOrClass: "Class 8 Annual",
        passingYear: 2025,
        gpaObtained: 4.55,
        conductRating: "Good"
      }
    ]
  },
  {
    id: "std-007",
    studentCode: "DIMS-2026-0607",
    roll: 7,
    nameEnglish: "Fahim Ahmed",
    nameBangla: "ফাহিম আহমেদ",
    className: "Class 9",
    section: "Padma",
    gender: "male",
    dob: "2010-12-01",
    bloodGroup: "A-",
    birthRegNumber: "20102692015099881",
    religion: "Islam",
    fatherName: "Jashim Uddin",
    fatherNameBangla: "জসীম উদ্দীন",
    motherName: "Rokeya Begum",
    motherNameBangla: "রোকেয়া বেগম",
    guardianName: "Jashim Uddin",
    guardianRelation: "Father",
    guardianPhone: "+8801552334455",
    emergencyContact: "+8801712001122",
    presentAddress: "Malibagh Chowdhury Para, Dhaka",
    permanentAddress: "Vill: Matlab, Dist: Chandpur",
    upazila: "Ramna",
    district: "Dhaka",
    admissionDate: "2022-01-14",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
    totalFeesDue: 1500,
    totalFeesPaid: 17000,
    attendanceRate: 89.2,
    lastExamGPA: 4.25,
    gpa: 4.25,
    extracurricular: {
      clubs: ["Scout Unit", "Science Club"],
      sports: ["Football", "Running (100m Sprint)"],
      leadershipRoles: ["Scout Squad Leader"],
      hobbies: ["Model Aeroplanes", "Electronics Assembly"],
      achievements: []
    },
    medicalHistory: {
      bloodGroup: "A-",
      knownAllergies: ["None"],
      chronicConditions: ["None"],
      regularMedications: ["None"],
      primaryPhysicianName: "Dr. M. Rahman",
      primaryPhysicianPhone: "+8801711229900",
      vaccinationStatus: "Complete"
    },
    emergencyContactInfo: {
      primaryContact: {
        name: "Jashim Uddin",
        relation: "Father",
        phonePrimary: "+8801552334455",
        addressOrWorkplace: "Malibagh, Dhaka",
        isAuthorizedForPickup: true
      },
      secondaryContact: {
        name: "Rokeya Begum",
        relation: "Mother",
        phonePrimary: "+8801712001122",
        addressOrWorkplace: "Malibagh, Dhaka",
        isAuthorizedForPickup: true
      },
      preferredHospital: "Dhaka Community Hospital, Moghbazar",
      ambulanceContact: "999"
    },
    previousAcademicRecords: [
      {
        id: "prev-008",
        previousSchoolName: "Motijheel Model High School and College",
        educationBoard: "Dhaka Board",
        examPassedOrClass: "Class 8 Annual",
        passingYear: 2025,
        gpaObtained: 4.25,
        conductRating: "Good"
      }
    ]
  },
  {
    id: "std-008",
    studentCode: "DIMS-2026-0608",
    roll: 8,
    nameEnglish: "Maimuna Akter",
    nameBangla: "মাইমুনা আক্তার",
    className: "Class 9",
    section: "Padma",
    gender: "female",
    dob: "2011-03-18",
    bloodGroup: "AB-",
    birthRegNumber: "20112692015088219",
    religion: "Islam",
    fatherName: "Sirajul Islam",
    fatherNameBangla: "সিরাজুল ইসলাম",
    motherName: "Bilkis Begum",
    motherNameBangla: "বিলকিস বেগম",
    guardianName: "Bilkis Begum",
    guardianRelation: "Mother",
    guardianPhone: "+8801720556677",
    emergencyContact: "+8801819334455",
    presentAddress: "Block E, Lalmatia, Dhaka",
    permanentAddress: "Vill: Ishwardi, Dist: Pabna",
    upazila: "Mohammadpur",
    district: "Dhaka",
    admissionDate: "2022-01-10",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    totalFeesDue: 0,
    totalFeesPaid: 18500,
    attendanceRate: 97.5,
    lastExamGPA: 4.95,
    gpa: 4.95,
    extracurricular: {
      clubs: ["English Language & Spelling Club", "Red Crescent Youth", "Science & Math Club"],
      sports: ["Badminton", "Table Tennis"],
      leadershipRoles: ["Assistant Class Prefect"],
      hobbies: ["Creative Writing in English & Bangla", "Origami", "Sketching"],
      achievements: [
        {
          id: "ach-009",
          title: "National English Spelling Bee Divisional Finalist",
          year: 2025,
          category: "olympiad",
          level: "Division",
          position: "Top 10 Finalist",
          description: "Represented Dhaka Division in National Television Spelling Bee Contest."
        }
      ]
    },
    medicalHistory: {
      bloodGroup: "AB-",
      knownAllergies: ["None"],
      chronicConditions: ["None"],
      regularMedications: ["None"],
      primaryPhysicianName: "Dr. Mahmuda Begum, MBBS, DCH",
      primaryPhysicianPhone: "+8801712445566",
      vaccinationStatus: "Complete"
    },
    emergencyContactInfo: {
      primaryContact: {
        name: "Bilkis Begum",
        relation: "Mother",
        phonePrimary: "+8801720556677",
        addressOrWorkplace: "Lalmatia, Dhaka",
        isAuthorizedForPickup: true
      },
      secondaryContact: {
        name: "Sirajul Islam",
        relation: "Father",
        phonePrimary: "+8801819334455",
        addressOrWorkplace: "Lalmatia, Dhaka",
        isAuthorizedForPickup: true
      },
      preferredHospital: "Ibn Sina Medical College Hospital, Kallyanpur / Dhanmondi",
      ambulanceContact: "999"
    },
    previousAcademicRecords: [
      {
        id: "prev-009",
        previousSchoolName: "Lalmatia Girls' High School",
        educationBoard: "Dhaka Board",
        examPassedOrClass: "Class 8 Annual",
        passingYear: 2025,
        gpaObtained: 4.95,
        conductRating: "Excellent"
      }
    ]
  }
];

export const initialTeachers: Teacher[] = [
  {
    id: "tch-001",
    teacherCode: "T-101",
    nameEnglish: "Prof. Md. Anwar Hossain",
    nameBangla: "অধ্যাপক মোঃ আনোয়ার হোসেন",
    designation: "Headmaster & Principal",
    designationBangla: "প্রধান শিক্ষক ও অধ্যক্ষ",
    department: "Administration & Physics",
    phone: "+8801711002233",
    email: "principal@school.edu.bd",
    nid: "19742692015000123",
    bloodGroup: "O+",
    joiningDate: "2012-03-01",
    basicSalary: 45000,
    bankAccountNo: "Sonali Bank 020000458912",
    bkashNumber: "+8801711002233",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    assignedClasses: [
      { className: "Class 10", section: "Science", subject: "Physics" },
      { className: "Class 9", section: "Padma", subject: "Physics" }
    ]
  },
  {
    id: "tch-002",
    teacherCode: "T-102",
    nameEnglish: "Begum Nazma Sultana",
    nameBangla: "বেগম নাজমা সুলতানা",
    designation: "Senior Assistant Teacher (Bangla)",
    designationBangla: "সিনিয়র সহকারী শিক্ষক (বাংলা)",
    department: "Bangla",
    phone: "+8801819223344",
    email: "nazma.sultana@school.edu.bd",
    nid: "19802692015000456",
    bloodGroup: "A+",
    joiningDate: "2015-06-15",
    basicSalary: 32000,
    bankAccountNo: "Agrani Bank 010000984512",
    bkashNumber: "+8801819223344",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    assignedClasses: [
      { className: "Class 9", section: "Padma", subject: "Bangla 1st & 2nd Paper" },
      { className: "Class 8", section: "A", subject: "Bangla" }
    ]
  },
  {
    id: "tch-003",
    teacherCode: "T-103",
    nameEnglish: "Md. Tariqul Islam",
    nameBangla: "মোঃ তারিকুল ইসলাম",
    designation: "Senior Teacher (Mathematics)",
    designationBangla: "সিনিয়র শিক্ষক (গণিত)",
    department: "Mathematics",
    phone: "+8801715443322",
    email: "tariqul.math@school.edu.bd",
    nid: "19852692015000789",
    bloodGroup: "B+",
    joiningDate: "2016-01-10",
    basicSalary: 30000,
    bankAccountNo: "Janata Bank 030000762391",
    bkashNumber: "+8801715443322",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    assignedClasses: [
      { className: "Class 9", section: "Padma", subject: "General Mathematics" },
      { className: "Class 9", section: "Padma", subject: "Higher Mathematics" }
    ]
  },
  {
    id: "tch-004",
    teacherCode: "T-104",
    nameEnglish: "A.H.M. Rezwanul Haque",
    nameBangla: "এ.এইচ.এম. রেজওয়ানুল হক",
    designation: "Lecturer (English)",
    designationBangla: "প্রভাষক (ইংরেজি)",
    department: "English",
    phone: "+8801912556677",
    email: "rezwan.eng@school.edu.bd",
    nid: "19882692015000999",
    bloodGroup: "AB+",
    joiningDate: "2018-09-01",
    basicSalary: 28000,
    bankAccountNo: "Rupali Bank 040000129845",
    bkashNumber: "+8801912556677",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    assignedClasses: [
      { className: "Class 9", section: "Padma", subject: "English 1st & 2nd Paper" },
      { className: "Class 10", section: "A", subject: "English" }
    ]
  },
  {
    id: "tch-005",
    teacherCode: "T-105",
    nameEnglish: "Mahbubur Rahman",
    nameBangla: "মাহবুবুর রহমান",
    designation: "Senior Accounts Officer",
    designationBangla: "প্রধান হিসাবরক্ষণ কর্মকর্তা",
    department: "Accounts & Finance",
    phone: "+8801671889900",
    email: "accounts@school.edu.bd",
    nid: "19832692015000333",
    bloodGroup: "O+",
    joiningDate: "2014-04-01",
    basicSalary: 27000,
    bankAccountNo: "Dutch-Bangla Bank 115100458712",
    bkashNumber: "+8801671889900",
    avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
    assignedClasses: []
  }
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: "att-001",
    studentId: "std-001",
    studentName: "Sadia Sultana",
    studentRoll: 1,
    className: "Class 9",
    section: "Padma",
    date: "2026-08-29",
    status: "present",
    inTime: "08:12 AM",
    markedBy: "tch-003",
    markedByName: "Md. Tariqul Islam",
    smsSent: false,
    smsStatus: "not_sent"
  },
  {
    id: "att-002",
    studentId: "std-002",
    studentName: "Tanvir Hasan",
    studentRoll: 2,
    className: "Class 9",
    section: "Padma",
    date: "2026-08-29",
    status: "present",
    inTime: "08:20 AM",
    markedBy: "tch-003",
    markedByName: "Md. Tariqul Islam",
    smsSent: false,
    smsStatus: "not_sent"
  },
  {
    id: "att-003",
    studentId: "std-003",
    studentName: "Anika Tabassum",
    studentRoll: 3,
    className: "Class 9",
    section: "Padma",
    date: "2026-08-29",
    status: "present",
    inTime: "08:05 AM",
    markedBy: "tch-003",
    markedByName: "Md. Tariqul Islam",
    smsSent: false,
    smsStatus: "not_sent"
  },
  {
    id: "att-004",
    studentId: "std-004",
    studentName: "Mahmudur Rahman",
    studentRoll: 4,
    className: "Class 9",
    section: "Padma",
    date: "2026-08-29",
    status: "absent",
    markedBy: "tch-003",
    markedByName: "Md. Tariqul Islam",
    smsSent: true,
    smsStatus: "delivered",
    remarks: "Automated Absence SMS dispatched to guardian +8801715667788"
  },
  {
    id: "att-005",
    studentId: "std-005",
    studentName: "Nusrat Jahan",
    studentRoll: 5,
    className: "Class 9",
    section: "Padma",
    date: "2026-08-29",
    status: "present",
    inTime: "08:24 AM",
    markedBy: "tch-003",
    markedByName: "Md. Tariqul Islam",
    smsSent: false,
    smsStatus: "not_sent"
  },
  {
    id: "att-006",
    studentId: "std-006",
    studentName: "Pritom Roy",
    studentRoll: 6,
    className: "Class 9",
    section: "Padma",
    date: "2026-08-29",
    status: "late",
    inTime: "08:45 AM",
    markedBy: "tch-003",
    markedByName: "Md. Tariqul Islam",
    smsSent: true,
    smsStatus: "delivered",
    remarks: "Late entry 15 mins past assembly"
  },
  {
    id: "att-007",
    studentId: "std-007",
    studentName: "Fahim Ahmed",
    studentRoll: 7,
    className: "Class 9",
    section: "Padma",
    date: "2026-08-29",
    status: "present",
    inTime: "08:18 AM",
    markedBy: "tch-003",
    markedByName: "Md. Tariqul Islam",
    smsSent: false,
    smsStatus: "not_sent"
  },
  {
    id: "att-008",
    studentId: "std-008",
    studentName: "Maimuna Akter",
    studentRoll: 8,
    className: "Class 9",
    section: "Padma",
    date: "2026-08-29",
    status: "present",
    inTime: "08:10 AM",
    markedBy: "tch-003",
    markedByName: "Md. Tariqul Islam",
    smsSent: false,
    smsStatus: "not_sent"
  }
];

export const initialExamGrades: ExamGradeRecord[] = [
  {
    id: "grd-001",
    studentId: "std-001",
    studentName: "Sadia Sultana",
    studentRoll: 1,
    className: "Class 9",
    section: "Padma",
    examType: "mid_term",
    examYear: 2026,
    publishedDate: "2026-07-25",
    attendancePercentage: 96.8,
    conductRemarks: "Outstanding academic dedication, leadership in science club.",
    positionInClass: 1,
    positionInSection: 1,
    isPassed: true,
    percentage: 91.8,
    totalMarks: 735,
    totalFullMarks: 800,
    gpa: 5.00,
    finalGrade: "A+",
    subjects: [
      { subjectCode: "101", subjectName: "Bangla 1st Paper", subjectNameBangla: "বাংলা ১ম পত্র", writtenMarks: 62, mcqMarks: 28, practicalMarks: 0, obtainedMarks: 90, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "102", subjectName: "Bangla 2nd Paper", subjectNameBangla: "বাংলা ২য় পত্র", writtenMarks: 60, mcqMarks: 27, practicalMarks: 0, obtainedMarks: 87, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "107", subjectName: "English 1st Paper", subjectNameBangla: "ইংরেজি ১ম পত্র", writtenMarks: 88, mcqMarks: 0, practicalMarks: 0, obtainedMarks: 88, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "108", subjectName: "English 2nd Paper", subjectNameBangla: "ইংরেজি ২য় পত্র", writtenMarks: 92, mcqMarks: 0, practicalMarks: 0, obtainedMarks: 92, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "109", subjectName: "General Mathematics", subjectNameBangla: "সাধারণ গণিত", writtenMarks: 68, mcqMarks: 29, practicalMarks: 0, obtainedMarks: 97, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "136", subjectName: "Physics", subjectNameBangla: "পদার্থবিজ্ঞান", writtenMarks: 45, mcqMarks: 22, practicalMarks: 24, obtainedMarks: 91, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "137", subjectName: "Chemistry", subjectNameBangla: "রসায়ন", writtenMarks: 47, mcqMarks: 23, practicalMarks: 25, obtainedMarks: 95, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "126", subjectName: "Higher Mathematics (4th)", subjectNameBangla: "উচ্চতর গণিত (৪র্থ)", writtenMarks: 46, mcqMarks: 24, practicalMarks: 25, obtainedMarks: 95, fullMarks: 100, grade: "A+", gradePoint: 5.0, isOptional: true }
    ]
  },
  {
    id: "grd-002",
    studentId: "std-002",
    studentName: "Tanvir Hasan",
    studentRoll: 2,
    className: "Class 9",
    section: "Padma",
    examType: "mid_term",
    examYear: 2026,
    publishedDate: "2026-07-25",
    attendancePercentage: 92.4,
    conductRemarks: "Attentive in class, highly skilled in problem solving.",
    positionInClass: 2,
    positionInSection: 2,
    isPassed: true,
    percentage: 86.5,
    totalMarks: 692,
    totalFullMarks: 800,
    gpa: 4.88,
    finalGrade: "A",
    subjects: [
      { subjectCode: "101", subjectName: "Bangla 1st Paper", subjectNameBangla: "বাংলা ১ম পত্র", writtenMarks: 55, mcqMarks: 24, practicalMarks: 0, obtainedMarks: 79, fullMarks: 100, grade: "A", gradePoint: 4.0 },
      { subjectCode: "102", subjectName: "Bangla 2nd Paper", subjectNameBangla: "বাংলা ২য় পত্র", writtenMarks: 58, mcqMarks: 26, practicalMarks: 0, obtainedMarks: 84, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "107", subjectName: "English 1st Paper", subjectNameBangla: "ইংরেজি ১ম পত্র", writtenMarks: 82, mcqMarks: 0, practicalMarks: 0, obtainedMarks: 82, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "108", subjectName: "English 2nd Paper", subjectNameBangla: "ইংরেজি ২য় পত্র", writtenMarks: 85, mcqMarks: 0, practicalMarks: 0, obtainedMarks: 85, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "109", subjectName: "General Mathematics", subjectNameBangla: "সাধারণ গণিত", writtenMarks: 65, mcqMarks: 28, practicalMarks: 0, obtainedMarks: 93, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "136", subjectName: "Physics", subjectNameBangla: "পদার্থবিজ্ঞান", writtenMarks: 43, mcqMarks: 20, practicalMarks: 23, obtainedMarks: 86, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "137", subjectName: "Chemistry", subjectNameBangla: "রসায়ন", writtenMarks: 41, mcqMarks: 21, practicalMarks: 21, obtainedMarks: 83, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "126", subjectName: "Higher Mathematics (4th)", subjectNameBangla: "উচ্চতর গণিত (৪র্থ)", writtenMarks: 40, mcqMarks: 20, practicalMarks: 20, obtainedMarks: 80, fullMarks: 100, grade: "A+", gradePoint: 5.0, isOptional: true }
    ]
  },
  {
    id: "grd-003",
    studentId: "std-003",
    studentName: "Anika Tabassum",
    studentRoll: 3,
    className: "Class 9",
    section: "Padma",
    examType: "mid_term",
    examYear: 2026,
    publishedDate: "2026-07-25",
    attendancePercentage: 98.2,
    conductRemarks: "Exemplary conduct and punctuality.",
    positionInClass: 3,
    positionInSection: 3,
    isPassed: true,
    percentage: 90.1,
    totalMarks: 721,
    totalFullMarks: 800,
    gpa: 5.00,
    finalGrade: "A+",
    subjects: [
      { subjectCode: "101", subjectName: "Bangla 1st Paper", subjectNameBangla: "বাংলা ১ম পত্র", writtenMarks: 60, mcqMarks: 26, practicalMarks: 0, obtainedMarks: 86, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "102", subjectName: "Bangla 2nd Paper", subjectNameBangla: "বাংলা ২য় পত্র", writtenMarks: 61, mcqMarks: 28, practicalMarks: 0, obtainedMarks: 89, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "107", subjectName: "English 1st Paper", subjectNameBangla: "ইংরেজি ১ম পত্র", writtenMarks: 90, mcqMarks: 0, practicalMarks: 0, obtainedMarks: 90, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "108", subjectName: "English 2nd Paper", subjectNameBangla: "ইংরেজি ২য় পত্র", writtenMarks: 91, mcqMarks: 0, practicalMarks: 0, obtainedMarks: 91, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "109", subjectName: "General Mathematics", subjectNameBangla: "সাধারণ গণিত", writtenMarks: 66, mcqMarks: 29, practicalMarks: 0, obtainedMarks: 95, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "136", subjectName: "Physics", subjectNameBangla: "পদার্থবিজ্ঞান", writtenMarks: 46, mcqMarks: 22, practicalMarks: 24, obtainedMarks: 92, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "137", subjectName: "Chemistry", subjectNameBangla: "রসায়ন", writtenMarks: 44, mcqMarks: 20, practicalMarks: 24, obtainedMarks: 88, fullMarks: 100, grade: "A+", gradePoint: 5.0 },
      { subjectCode: "126", subjectName: "Higher Mathematics (4th)", subjectNameBangla: "উচ্চতর গণিত (৪র্থ)", writtenMarks: 45, mcqMarks: 23, practicalMarks: 22, obtainedMarks: 90, fullMarks: 100, grade: "A+", gradePoint: 5.0, isOptional: true }
    ]
  }
];

export const initialPayrollRecords: TeacherPayroll[] = [
  {
    id: "pyr-001",
    voucherNo: "PAY-2026-08-01",
    teacherId: "tch-001",
    teacherName: "Prof. Md. Anwar Hossain",
    teacherNameBangla: "অধ্যাপক মোঃ আনোয়ার হোসেন",
    designation: "Headmaster & Principal",
    month: "August 2026",
    monthBangla: "আগস্ট ২০২৬",
    year: 2026,
    basicSalary: 45000,
    houseRentAllowance: 18000,
    medicalAllowance: 1500,
    conveyanceAllowance: 3000,
    festivalBonus: 0,
    specialAllowance: 2500,
    grossSalary: 70000,
    providentFundDeduction: 4500,
    taxDeduction: 1500,
    advanceLoanDeduction: 0,
    totalDeductions: 6000,
    netPayable: 64000,
    status: "disbursed",
    paymentMethod: "Bank Transfer",
    disbursedDate: "2026-08-28",
    transactionRef: "SONALI-TXN-8823901",
    remarks: "August salary disbursed via Sonali Bank Corporate Account"
  },
  {
    id: "pyr-002",
    voucherNo: "PAY-2026-08-02",
    teacherId: "tch-002",
    teacherName: "Begum Nazma Sultana",
    teacherNameBangla: "বেগম নাজমা সুলতানা",
    designation: "Senior Assistant Teacher (Bangla)",
    month: "August 2026",
    monthBangla: "আগস্ট ২০২৬",
    year: 2026,
    basicSalary: 32000,
    houseRentAllowance: 12800,
    medicalAllowance: 1500,
    conveyanceAllowance: 2000,
    festivalBonus: 0,
    specialAllowance: 0,
    grossSalary: 48300,
    providentFundDeduction: 3200,
    taxDeduction: 0,
    advanceLoanDeduction: 0,
    totalDeductions: 3200,
    netPayable: 45100,
    status: "disbursed",
    paymentMethod: "bKash",
    disbursedDate: "2026-08-28",
    transactionRef: "BKASH-PAY-99120348",
    remarks: "Disbursed via bKash Payroll API"
  },
  {
    id: "pyr-003",
    voucherNo: "PAY-2026-08-03",
    teacherId: "tch-003",
    teacherName: "Md. Tariqul Islam",
    teacherNameBangla: "মোঃ তারিকুল ইসলাম",
    designation: "Senior Teacher (Mathematics)",
    month: "August 2026",
    monthBangla: "আগস্ট ২০২৬",
    year: 2026,
    basicSalary: 30000,
    houseRentAllowance: 12000,
    medicalAllowance: 1500,
    conveyanceAllowance: 2000,
    festivalBonus: 0,
    specialAllowance: 0,
    grossSalary: 45500,
    providentFundDeduction: 3000,
    taxDeduction: 0,
    advanceLoanDeduction: 0,
    totalDeductions: 3000,
    netPayable: 42500,
    status: "disbursed",
    paymentMethod: "Bank Transfer",
    disbursedDate: "2026-08-28",
    transactionRef: "JANATA-TXN-110293"
  },
  {
    id: "pyr-004",
    voucherNo: "PAY-2026-08-04",
    teacherId: "tch-004",
    teacherName: "A.H.M. Rezwanul Haque",
    teacherNameBangla: "এ.এইচ.এম. রেজওয়ানুল হক",
    designation: "Lecturer (English)",
    month: "August 2026",
    monthBangla: "আগস্ট ২০২৬",
    year: 2026,
    basicSalary: 28000,
    houseRentAllowance: 11200,
    medicalAllowance: 1500,
    conveyanceAllowance: 2000,
    festivalBonus: 0,
    specialAllowance: 0,
    grossSalary: 42700,
    providentFundDeduction: 2800,
    taxDeduction: 0,
    advanceLoanDeduction: 0,
    totalDeductions: 2800,
    netPayable: 39900,
    status: "pending",
    paymentMethod: "bKash",
    remarks: "Awaiting Headmaster final signature authorization"
  },
  {
    id: "pyr-005",
    voucherNo: "PAY-2026-08-05",
    teacherId: "tch-005",
    teacherName: "Mahbubur Rahman",
    teacherNameBangla: "মাহবুবুর রহমান",
    designation: "Senior Accounts Officer",
    month: "August 2026",
    monthBangla: "আগস্ট ২০২৬",
    year: 2026,
    basicSalary: 27000,
    houseRentAllowance: 10800,
    medicalAllowance: 1500,
    conveyanceAllowance: 1500,
    festivalBonus: 0,
    specialAllowance: 0,
    grossSalary: 40800,
    providentFundDeduction: 2700,
    taxDeduction: 0,
    advanceLoanDeduction: 0,
    totalDeductions: 2700,
    netPayable: 38100,
    status: "pending",
    paymentMethod: "Bank Transfer"
  }
];

export const initialSMSNotifications: SMSNotification[] = [
  {
    id: "sms-001",
    recipientPhone: "+8801715667788",
    studentId: "std-004",
    studentName: "Mahmudur Rahman",
    guardianName: "Abdur Rahman",
    messageBangla: "সম্মানিত অভিভাবক, আপনার সন্তান মাহমুদুর রহমান (রোল ৪, শ্রেণি ৯) আজ ২৯/০৮/২০২৬ বিদ্যালয়ে অনুপস্থিত ছিল। - ঢাকা মডেল হাই স্কুল",
    messageEnglish: "Dear Guardian, your ward Mahmudur Rahman (Roll 4, Class 9) was absent today 29/08/2026. - Dhaka Model High School",
    type: "attendance_absence",
    status: "delivered",
    gatewayResponseId: "GP-SMS-20260829-84729",
    costBDT: 0.45,
    sentAt: "2026-08-29 09:15 AM",
    characterCount: 92
  },
  {
    id: "sms-002",
    recipientPhone: "+8801718990011",
    studentId: "std-006",
    studentName: "Pritom Roy",
    guardianName: "Subhash Roy",
    messageBangla: "সম্মানিত অভিভাবক, আপনার সন্তান প্রীতম রায় আজ বিদ্যালয়ে ১৫ মিনিট দেরিতে প্রবেশ করেছে। - ঢাকা মডেল হাই স্কুল",
    messageEnglish: "Dear Guardian, your ward Pritom Roy entered school 15 minutes late today. - Dhaka Model High School",
    type: "attendance_late",
    status: "delivered",
    gatewayResponseId: "TT-SMS-20260829-10928",
    costBDT: 0.45,
    sentAt: "2026-08-29 08:50 AM",
    characterCount: 78
  },
  {
    id: "sms-003",
    recipientPhone: "+8801712345678",
    studentId: "std-001",
    studentName: "Sadia Sultana",
    guardianName: "Rafiqul Islam",
    messageBangla: "অভিনন্দন! সাদিয়া সুলতানা অর্ধবার্ষিক পরীক্ষায় GPA 5.00 পেয়ে শ্রেণিতে ১ম স্থান অধিকার করেছে। - ঢাকা মডেল স্কুল",
    messageEnglish: "Congratulations! Sadia Sultana achieved GPA 5.00 (1st Position) in Mid-Term Examination. - Dhaka Model School",
    type: "exam_result",
    status: "delivered",
    gatewayResponseId: "BL-SMS-20260725-33921",
    costBDT: 0.45,
    sentAt: "2026-07-25 04:30 PM",
    characterCount: 88
  }
];

export const initialNotices: SchoolNotice[] = [
  {
    id: "not-001",
    titleEnglish: "Pre-Test & Model Test Examination Routine 2026",
    titleBangla: "প্রাক-নির্বাচনী ও মডেল টেস্ট পরীক্ষা ২০২৬ এর সময়সূচি",
    contentEnglish: "The SSC Pre-Test Examination for Class 9 and 10 will commence from 15th September 2026. Detailed subject routines have been published on the notice board and student portal.",
    contentBangla: "নবম ও দশম শ্রেণির প্রাক-নির্বাচনী পরীক্ষা আগামী ১৫ই সেপ্টেম্বর ২০২৬ থেকে শুরু হবে। বিস্তারিত পরীক্ষার রুটিন নোটিশ বোর্ড ও শিক্ষার্থী পোর্টালে প্রকাশ করা হয়েছে।",
    category: "exam",
    priority: "high",
    publishedBy: "Prof. Md. Anwar Hossain (Headmaster)",
    publishedDate: "2026-08-25",
    targetAudience: "students_guardians",
    smsBroadcastSent: true
  },
  {
    id: "not-002",
    titleEnglish: "Urgent Weather Advisory: Special Assembly Cancellation",
    titleBangla: "জরুরি আবহাওয়া সতর্কবার্তা: মর্নিং অ্যাসেম্বলি স্থগিত",
    contentEnglish: "Due to heavy torrential rainfall and waterlogging in low-lying Dhaka areas, morning physical assembly is cancelled. All students should proceed directly to classrooms.",
    contentBangla: "ভারী বর্ষণ ও জলাবদ্ধতার কারণে সকালের উন্মুক্ত সমাবেশ (অ্যাসেম্বলি) স্থগিত ঘোষণা করা হলো। সকল শিক্ষার্থীকে সরাসরি শ্রেণিকক্ষে প্রবেশের নির্দেশ দেওয়া হচ্ছে।",
    category: "emergency",
    priority: "urgent",
    publishedBy: "Administration Office",
    publishedDate: "2026-08-29",
    targetAudience: "all",
    smsBroadcastSent: true
  },
  {
    id: "not-003",
    titleEnglish: "Parent-Teacher Conference & Progress Report Distribution",
    titleBangla: "অভিভাবক-শিক্ষক মতবিনিময় সভা ও মূল্যায়ন রিপোর্ট বিতরণ",
    contentEnglish: "A general Parent-Teacher meeting for all sections of Class 6 to 10 will be held on Saturday, 5th September at 10:00 AM in the school auditorium.",
    contentBangla: "৬ষ্ঠ থেকে ১০ম শ্রেণির শিক্ষার্থীদের সার্বিক অগ্রগতি মূল্যায়নে আগামী শনিবার ৫ই সেপ্টেম্বর সকাল ১০:০০ টায় স্কুল অডিটোরিয়ামে অভিভাবক সমাবেশ অনুষ্ঠিত হবে।",
    category: "academic",
    priority: "normal",
    publishedBy: "Academic Committee",
    publishedDate: "2026-08-20",
    targetAudience: "students_guardians",
    smsBroadcastSent: false
  }
];

export const initialFeePayments: FeePayment[] = [
  {
    id: "fee-001",
    receiptNo: "REC-2026-08-101",
    studentId: "std-001",
    studentName: "Sadia Sultana",
    studentRoll: 1,
    className: "Class 9",
    section: "Padma",
    feeType: "Tuition Fee",
    feeTypeBangla: "মাসিক বেতন ও আইসিটি চার্জ",
    month: "August 2026",
    amount: 1500,
    fineAmount: 0,
    discountAmount: 0,
    netAmount: 1500,
    paymentMethod: "bKash",
    transactionId: "BK-9988221144",
    paidDate: "2026-08-05",
    collectedBy: "Online Gateway (bKash)",
    status: "paid"
  },
  {
    id: "fee-002",
    receiptNo: "REC-2026-08-102",
    studentId: "std-003",
    studentName: "Anika Tabassum",
    studentRoll: 3,
    className: "Class 9",
    section: "Padma",
    feeType: "Tuition Fee",
    feeTypeBangla: "মাসিক বেতন",
    month: "August 2026",
    amount: 1500,
    fineAmount: 0,
    discountAmount: 0,
    netAmount: 1500,
    paymentMethod: "Nagad",
    transactionId: "NGD-7722119933",
    paidDate: "2026-08-07",
    collectedBy: "Online Gateway (Nagad)",
    status: "paid"
  },
  {
    id: "fee-003",
    receiptNo: "REC-2026-08-103",
    studentId: "std-005",
    studentName: "Nusrat Jahan",
    studentRoll: 5,
    className: "Class 9",
    section: "Padma",
    feeType: "Exam Fee",
    feeTypeBangla: "মডেল টেস্ট ফি",
    month: "August 2026",
    amount: 800,
    fineAmount: 0,
    discountAmount: 0,
    netAmount: 800,
    paymentMethod: "Cash",
    transactionId: "CASH-REC-041",
    paidDate: "2026-08-12",
    collectedBy: "Mahbubur Rahman (Accounts)",
    status: "paid"
  }
];

export const initialGuardianInquiries: GuardianInquiry[] = [
  {
    id: "inq-001",
    studentId: "std-004",
    studentName: "Mahmudur Rahman",
    guardianName: "Abdur Rahman",
    guardianPhone: "+8801715667788",
    subject: "Special permission for extra mathematics coaching",
    message: "Respected Headmaster, Mahmudur had missed 2 classes due to seasonal fever. Can he attend the special Math remedial session with Sir Tariqul Islam?",
    status: "answered",
    createdAt: "2026-08-28 11:30 AM",
    response: "Yes, Abdur Rahman Shaheb. Mahmudur is welcome to attend the 3:30 PM remedial session on Mondays and Wednesdays in Room 302.",
    respondedBy: "Md. Tariqul Islam (Math Teacher)",
    respondedAt: "2026-08-28 02:15 PM"
  },
  {
    id: "inq-002",
    studentId: "std-002",
    studentName: "Tanvir Hasan",
    guardianName: "Kamrul Hasan",
    guardianPhone: "+8801819876543",
    subject: "Science Olympiad regional registration confirmation",
    message: "Has Tanvir's nomination for the Bangladesh National Science Olympiad 2026 been forwarded from the school?",
    status: "open",
    createdAt: "2026-08-29 08:30 AM"
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "aud-001",
    timestamp: "2026-08-29 08:45:12",
    userName: "Md. Tariqul Islam",
    userRole: "teacher",
    ipAddress: "103.145.118.24 (Dhaka, BD)",
    action: "ATTENDANCE_RECORDED",
    module: "Attendance",
    status: "success",
    details: "Marked Class 9 Section Padma daily attendance (7 Present, 1 Absent, 1 Late). Triggered 2 SMS notifications."
  },
  {
    id: "aud-002",
    timestamp: "2026-08-28 16:20:05",
    userName: "Prof. Md. Anwar Hossain",
    userRole: "admin",
    ipAddress: "103.145.118.10 (School Admin LAN)",
    action: "PAYROLL_APPROVAL",
    module: "Payroll",
    status: "success",
    details: "Approved August 2026 faculty payroll vouchers totaling ৳2,29,600."
  },
  {
    id: "aud-003",
    timestamp: "2026-08-28 11:15:40",
    userName: "Mahbubur Rahman",
    userRole: "staff",
    ipAddress: "103.145.118.15 (Accounts Desk)",
    action: "FEE_RECEIPT_ISSUED",
    module: "Fees",
    status: "success",
    details: "Issued money receipt #REC-2026-08-103 for Student ID DIMS-2026-0605 (Nusrat Jahan) - ৳800 (Exam Fee)."
  },
  {
    id: "aud-004",
    timestamp: "2026-08-27 14:02:18",
    userName: "Super Administrator",
    userRole: "super_admin",
    ipAddress: "118.179.88.42 (BTTB Optical Fiber)",
    action: "DATABASE_BACKUP_SNAPSHOT",
    module: "System & MySQL",
    status: "success",
    details: "Automated MySQL database schema and transaction dump created: sonarpathshala_backup_20260827.sql (SHA-256 verified)."
  }
];
